### Get user's upload requests

GET {{host}}/api/v1/users/{{userId}}/upload/requests

### Create user's upload requests

POST {{host}}/api/v1/users/{{userId}}/upload/requests

["img.png", "video.mp4"]
