externalDocs:
  description: General Docs
  url: https://github.com/S1ckret-Labs/family-archive-docs
info:
  contact:
    email: support@some_email.com
    name: s1ckret-labs
    url: https://github.com/S1ckret-Labs
paths:
  /api/v1/users/{id}/tree:
    get:
      description: Get the user's object tree with optional parameters
      operationId: get-tree
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Root Object ID
        in: query
        name: root_object_id
        type: integer
      - description: Depth
        in: query
        name: depth
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get user's object tree
  /api/v1/users/{id}/upload/requests:
    get:
      description: Get the upload requests for a user
      operationId: get-upload-requests
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user's upload requests
    post:
      consumes:
      - application/json
      description: Create upload requests for a user
      operationId: create-upload-requests
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create upload requests
  /health:
    get:
      description: Get the health status of the application
      operationId: get-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get health status
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
